#!/usr/bin/env bash
# 7-highlander: Infinite loop that traps SIGTERM and prints a message instead of terminating

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
